# Generated by Django 4.1.13 on 2025-09-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='action_type',
            field=models.IntegerField(default=1),
        ),
    ]
