# Generated by Django 4.1.13 on 2025-09-24 13:52

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_user_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('actions', djongo.models.fields.JSONField(blank=True, default=list)),
                ('action_type', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
    ]
